# Change these first
owner: CymaSuite # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: App Cymasuite
    url: https://app.cymasuite.com
  - name: Api Cymasuite
    url: https://api.cymasuite.com/api/v1/healthcheck
  - name: Web Cymasuite
    url: https://web.cymasuite.com
  - name: Servicio de impuestos interno
    url: https://homer.sii.cl/
  - name: Zeus
    url: https://zeusr.sii.cl
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: cymasuite.github.io
  baseUrl: /upptime
  logoUrl: https://www.cymasuite.com/img/logo-cymasuite.svg
  name: Upptime
  theme: light
  introTitle: "**Upptime** es el monitor de tiempo de actividad de CymaSuite y los estados de las páginas"
  introMessage: Esta es una página de estado de muestra que utiliza **real-time** Datos de nuestra [GitHub repository](https://github.com/CymaSuite/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/CymaSuite/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/CymaSuite/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
