# Change these first
owner: CymaSuite # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Sitio Web Oficial Cymasuite
    url: https://www.cymasuite.com
  - name: Sitio Web 2.0 Cymasuite
    url: https://web.cymasuite.com
  - name: Aplicación Web Cymasuite
    url: https://app.cymasuite.com
  - name: Api Cymasuite
    url: https://api.cymasuite.com/api/v1/healthcheck
  - name: Worker Cymasuite
    url: https://api.cymasuite.com/sidekiq
  - name: Documentación Developer
    url: https://api.cymasuite.com/api-docs/index.html
  - name: Servicio de impuestos interno
    url: https://homer.sii.cl
  - name: Zeus
    url: https://zeusr.sii.cl
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: cymasuite.github.io
  baseUrl: /upptime
  logoUrl: https://www.cymasuite.com/img/logo-cymasuite.svg
  name: Upptime
  theme: light
  introTitle: "**Servidor CymaSuite** ¿Está abajo, o soy solo yo?"
  introMessage: Monitorea el tiempo de actividad y disponibilidad de nuestras aplicaciones web, te brindamos una visión integral y transparente sobre el estado de nuestras soluciónes.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/CymaSuite/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
